### ISSUE TITLE
Solar input showing 800w when its 80w on delta pro

### ISSUE THREAD

**Issue by icemandk** [tolwi/hassio-ecoflow-cloud#19]
Running integration version 0.7.5 on Delta Pro

Solar input sensor >> sensor.deltapro_solar_in_power

excample sensor is showing : 800w when its actually generating 80w

**Comment by tolwi** [comment]
The solar input sensor is currently bound to `mppt.inWatts` - looks like it is wrong. 
Try to find the correct data key from diag dump, please.

**Comment by ekashuba** [comment]
I just received my Delta Pro's today and I've run into the same issue as icemandk.  I've looked through the diagnostic dump and I don't see any key other than "mppt.inWatts" which might contain the correct value.

Is there an easy way to tweak the code so that the value returned from Ecoflow can be divided by 10? 

 (Sorry if there's a simple answer to that -- I'm a total newb when it comes to Python).

**Comment by ekashuba** [comment]
OK -- I think I've come up with a quick workaround to this issue.  As I mentioned above, though, I have no idea what I'm doing so use this at your own risk!

I ended up making changes to 2 of the files in this integration.  The first change defines a new class to handle the solar input and divides the value of the solar input that it's getting from Ecoflow by 10.  The second change modifies the sensor for the solar input to use that new class.

In the /config/custom_components/ecoflow_cloud/sensor.py file I added a new class called "InWattsSolarSensorEntity" .  I don't know python so I just used the existing code as a model and then I tweaked it a bit by adding this code.  I'm not going to pretend to know what it's doing but here it is:

	class InWattsSolarSensorEntity(WattsSensorEntity):
	    _attr_icon = "mdi:solar-power-variant-outline"
	
	    def _update_value(self, val: Any) -> bool:
	        if self._attr_native_value != val/10:
	            self._attr_native_value = val/10
	            return True
	        else:
                return False

In the /config/custom_components/ecoflow_cloud/devices/delta_pro.py file I changed the way that the sensor using the "mppt.inWatts" value is configured so that it now uses the new class that was defined above:

 I changed this line in the delta_pro.py file:

        InWattsrSensorEntity(client, "mppt.inWatts", const.SOLAR_IN_POWER),

to this:

        InWattsSolarSensorEntity(client, "mppt.inWatts", const.SOLAR_IN_POWER),

Since I'm now using this new class in the delta_pro.py file I also needed to make sure that it was included in the header at the top of the delta_pro.py file:

        from ..sensor import LevelSensorEntity, WattsSensorEntity, RemainSensorEntity, TempSensorEntity, \
            CyclesSensorEntity, InWattsSensorEntity, InWattsSolarSensorEntity, OutWattsSensorEntity, VoltSensorEntity		

Once I made those changes I restarted Home Assistant and I'm now getting the correct values for my solar inputs.  I'm sure that there are better ways to handle this but this seems to be working for me.

**Comment by herbyak** [comment]
HI, I have the same issue on my DP Pro. Is somebody working on a solution for that? There should be an easy way to adjust that for us user!

**Comment by mattwells** [comment]
I descovered this "issue" while playing around putting the MQTT messages directly into InfluxDB. Apparently it is common for UPS to use deciwatt (1/10 a watt) and Ecoflow has also adopted it for this field, presumably because it gives more precision while not having to use a float or decimal.
