### ISSUE TITLE
Solar In Volts and In Amps gone?

### ISSUE THREAD

**Issue by shimfish** [tolwi/hassio-ecoflow-cloud#273]
I've just noticed that these entities are no longer available on my Delta 2 Max integration.

Did they go in the latest update or did EF stop providing them?

**Comment by foxthefox** [comment]
Since the new version >1.0 is using the official API, it might not get redistributed. I would guess that the DM2 still sends it.
I have the feeling that the official API is only delivering a few of the available datapoints.
On the other hand for DM2 at least the documentation says that in is there mppt.inVolt, mppt.inAmp.

**Comment by Nid01** [comment]
@shimfish I checked the file changes of delta2_max.py, but can't find anything which shows that such data existed.
Can you provide my more details so I can take another look?

**Comment by shimfish** [comment]
@Nid01 Not sure what I can provide you with.

All I can say is that when I first set it up, it gave me solar in volts and solar in amps for both mppt inputs and now it says "not provided". My history shows a graph for those values and then one day it just stops.

<img width="749" alt="image" src="https://github.com/user-attachments/assets/495e2cd2-2a66-44e7-9734-88035293acc0">

**Comment by shimfish** [comment]
Have finally got it together to submit a PR for this change.
