### ISSUE TITLE
Typo in Powerstream discharge_level public API 

### ISSUE THREAD

**Issue by giovanne123** [tolwi/hassio-ecoflow-cloud#309]
Powerstream 
public API 

Is:
number.powerstream_min_disharge_level

should:
number.powerstream_min_discharge_level

**Comment by Dev-Fabry** [comment]
@giovanne123 

Hi, What version were you using when you reported the problem?

With 1.1.0-pre6 and pre7 I see the correct sensor name (min_discharge_level).

**Comment by giovanne123** [comment]
@Dev-Fabry , 
1.1.0-pre6 - hm strange... maybe need to check again by updating to 1.1.0-pre7 and recreate the devices 🤔

But don't want to play too much at the moment because of #306

**Comment by Dev-Fabry** [comment]
The typo is still present in commented code (I have create a Pull request) but I don't in working code (and my sensor has the correct name)

**Comment by Dev-Fabry** [comment]
I definitely redownloaded the integration from scratch, because I wanted to make my own guide for ESPTemp and since I had already modified the code I redownloaded the integration to start from a clean version without my changes and then one step at a time try the changes (and report them in the guide)

**Comment by giovanne123** [comment]
Tested again with 1.1.0 and is fine.

Maybe on previous update from application API to public API I had some mixture of this entity.
