### ISSUE TITLE
Sponsorship?

### ISSUE THREAD

**Issue by AshleyJackson** [tolwi/hassio-ecoflow-cloud#45]
Hi @tolwi.

I really love the fact that you have created this. It has provided me with a way to update the firmware on my devices and use Home Assistant together.

Previously I was not updating my firmware and using https://github.com/vwt12eh8/hassio-ecoflow.

Would you be open to enabling Sponsorships on this Repository?
I would like to see this project grow and I beleive that people might be willing to pay you for your work here.

Thanks.

**Comment by tolwi** [comment]
Originally this integration was created as a personal pet project - I wanted to optimize charging strategy for my devices during last winter global power outages in Ukraine due to massive missile attacks. As it is said in readme it was not a goal to cover and support all available devices. And I don't want any kind of commercialization in this project.

**Comment by tolwi** [comment]
no, it is not.
