### ISSUE TITLE
Incorrect Input/Output values? kWh instead of Wh?

### ISSUE THREAD

**Issue by AshleyJackson** [tolwi/hassio-ecoflow-cloud#82]
Hello,

I own a Delta Pro and within the energy section of Home Assistant it is showing kWh generated and used.
![image](https://github.com/tolwi/hassio-ecoflow-cloud/assets/12793989/4a03305c-2c86-4ae2-969a-121de705b4de)

Is this value being converted incorrectly by the Integration?

Please let me know if you need any test data from me.
Thanks.

**Comment by knyghtryda** [comment]
@AshleyJackson @tolwi Just a reminder that first day integrations will always be strange, because the value stored is continually increasing.  That means the first time it gets picked up It will read your all time total.  After a day it will start to display your delta value, not cumulative value.  Here are my day and week values:
<img width="2300" alt="Screenshot 2023-07-18 at 8 48 30 AM" src="https://github.com/tolwi/hassio-ecoflow-cloud/assets/1226173/8e825fda-8fca-495f-ad85-37f4a48e57b8">
<img width="2300" alt="Screenshot 2023-07-18 at 8 48 30 AM" src="https://github.com/tolwi/hassio-ecoflow-cloud/assets/1226173/f547f78e-1bbc-494b-b940-13bf8a1e4dc1">
